#!/bin/bash
mkdir /var/www/flask-app/
cd /var/www/flask-app
python3 -m venv .venv
source /var/www/flask-app/.venv/bin/activate

pip install --upgrade pip
pip install Flask gunicorn
pip install -r requirements.txt

deactivate