name: Flask workflow
env:
  ENV_PACKAGE_NAME: "web_app_${{ github.sha }}.zip"

on:
  push:
    branches:
      - main
      - workflows
  pull_request:
    paths-ignore:
      - '**.md'


jobs:
  flask:
    name: "Flask"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
      AWS_BUCKET_NAME: "${{ secrets.AWS_BUCKET_NAME }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip
        id: zip
        run: zip -r ${{ env.ENV_PACKAGE_NAME }} ./ -x *.git* README.md 

      - name: Push to S3
        uses: shallwefootball/s3-upload-action@master
        id: s3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET_NAME }}

      
      
    